### ISSUE TITLE
Missing components in FormMain

### ISSUE THREAD

**Issue by sonjli** [MHumm/delphi-code-coverage-wizard-plus#3]
**Describe the bug**
Some missing components in MainForm.pas and so project can't compile

**To Reproduce**
1. Open project in Delphi
3. Open MainForm.pas
4. Change any line in pas
5. Save
6. Tipical Delphi error when dfm is not aligned with TMainForm class

**Expected behavior**
Compile without errors

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser edge
 - Delphi version 12

**Additional context**
Missing components in dfm and events links:
``` pascal
          object MemoClassPrefixExcluded: TMemo
            OnChange = MemoClassPrefixExcludedChange
          end
          object CheckBoxLimitNumberOfExecutionTime: TCheckBox
            OnClick = CheckBoxLimitNumberOfExecutionTimeClick
          end
          object NumberBoxLineExecutionCount: TNumberBox
          end
          object CheckBoxIncludeFileExtension: TCheckBox
            OnClick = CheckBoxIncludeFileExtensionClick
          end
```

**Comment by MHumm** [comment]
Oh dear...
Sorry for this. I'll try to look at it later on today.

**Comment by MHumm** [comment]
Ok, I fixed this along with the maximum number of the number box for defining how often a line of code shall be executed at maximum and when clicking a menu item in the left hand menu the description label at the top will be updated now already and not only when clicking somewhere on a control on the right hand side.
=> can you check whether this works now?

**Comment by sonjli** [comment]
Very good!
Thanks

**Comment by MHumm** [comment]
Thanks for the positive feedback. Now I'm struggling with a reported virus detection in the currently tagged version. Most likely some virus scanners flagged one of the command line executables contained as infected. I'll try to rebuild them from their source (not my open source project) later on. But I can still close this issue as fixed.
